# Generated by Django 3.2.19 on 2024-07-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240703_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
