# Generated by Django 3.2.19 on 2024-07-05 04:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240629_1327'),
        ('users', '0012_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('affiliate_link', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales', models.IntegerField(default=0)),
                ('author', models.CharField(default='Unknown Author', max_length=200)),
                ('pages', models.IntegerField(default=0)),
                ('publisher', models.CharField(default='Unknown Publisher', max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('isbn', models.CharField(default='Unknown ISBN', max_length=13)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('language', models.CharField(default='Unknown Language', max_length=100)),
                ('length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
