# Generated by Django 3.2.19 on 2024-07-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
