# Generated by Django 3.2.19 on 2024-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240626_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=200),
        ),
        migrations.AddField(
            model_name='ebook',
            name='language',
            field=models.CharField(default='Unknown Language', max_length=100),
        ),
        migrations.AddField(
            model_name='ebook',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ebook',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='publisher',
            field=models.CharField(default='Unknown Publisher', max_length=200),
        ),
        migrations.AddField(
            model_name='ebook',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ebook',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='isbn',
            field=models.CharField(default='Unknown ISBN', max_length=13),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
