# Generated by Django 3.2.19 on 2024-06-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240629_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='popularity_score',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='gadget',
            old_name='popularity_score',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='popularity_score',
            new_name='clicks',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='is_new',
        ),
    ]
