# Generated by Django 3.2.19 on 2024-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240629_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='clicks',
        ),
    ]
