# Generated by Django 3.2.19 on 2024-06-29 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240629_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ebook',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gadget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gadget',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gadget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laptop',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
